// This file was auto-generated by prisma-generator-typescript-interfaces

export enum ConsoleLogLevel {
  LOG = "LOG",
  INFO = "INFO",
  WARN = "WARN",
  ERROR = "ERROR",
  DEBUG = "DEBUG",
  VERBOSE = "VERBOSE"
}

export interface ConsoleLog {
  id: number;
  level: ConsoleLogLevel;
  message: string;
  createdAt: Date;
}
